Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -20,29 +20,42 @@ pool:
   vmImage: ubuntu-latest
 
 steps:
-- bash: |
-    echo "current folder: $(pwd)"
-    FROM_SOURCE=$(cat .node-version || cat .nvmrc)
-    ls .node-version && echo ".node-version found, value: '$(cat .node-version)'" || echo ".node-version not found" 
-    ls .nvmrc && echo ".nvmrc found, value: '$(cat .nvmrc)'" || echo ".nvmrc not found" 
-    echo "set FROM_SOURCE='$FROM_SOURCE'"
-    echo "##vso[task.setvariable variable=NODE_VERSION]$FROM_SOURCE"
-  displayName: 'Determine Node.js version from source'
+# - bash: |
+#     echo "current folder: $(pwd)"
+#     FROM_SOURCE=$(cat .node-version || cat .nvmrc)
+#     ls .node-version && echo ".node-version found, value: '$(cat .node-version)'" || echo ".node-version not found" 
+#     ls .nvmrc && echo ".nvmrc found, value: '$(cat .nvmrc)'" || echo ".nvmrc not found" 
+#     echo "set FROM_SOURCE='$FROM_SOURCE'"
+#     echo "##vso[task.setvariable variable=NODE_VERSION]$FROM_SOURCE"
+#   displayName: 'Determine Node.js version from source'
 
-- task: UseNode@1
-  inputs:
-    version: $(NODE_VERSION)
-  displayName: 'Set up Node.js'
+# - task: UseNode@1
+#   inputs:
+#     version: $(NODE_VERSION)
+#   displayName: 'Set up Node.js'
+
+# - bash: |
+#     echo "current folder: $(pwd)"
+#     yarn install --frozen-lockfile --no-progress --non-interactive
+#   displayName: 'Install node modules'
+
+# - bash: |
+#     yarn build
+#   displayName: 'Build'
 
 - bash: |
-    echo "current folder: $(pwd)"
-    yarn install --frozen-lockfile --no-progress --non-interactive
-  displayName: 'Install node modules'
+    timestamp=$(date +%s)
 
-- bash: |
-    yarn build
-  displayName: 'Build'
-
-- bash: |
-    az --version
-  displayName: 'test'
+    az storage blob download \
+      --name $(INPUT_FILE_NAME) \
+      --container-name input \
+      --file $timestamp.txt \
+      --account-key $(STORAGE_KEY)
+    
+    ls -la
+    
+    mkdir -p output
+    split --lines=$(MAX_ROWS_FILE) $timestamp output/timestamp
+    
+    ls -la output
+  displayName: 'split'
